const data = {
  medico_responsavel: 'JULIO CESAR FERREIRA LIMA',
  medico_responsavel_conselho: 'CREA',
  medico_responsavel_conselho_uf: 'CE',
  medico_responsavel_conselho_numero: '1231',
  paciente: 'MELISSE PONTES',
  data_nascimento: '10/08/1992',
  sexo: 'M',
  idade: 28,
  plano: 'VOCE BEM',
  cpf: '',
  dlp: '',
  telefone: '(85) 998614541',
  observacao_classificacao: 'RETORNO',
  observacao_cids: '',
  queixa: 'Teste de Queixa principal',
  tempo_doenca: '10 dias',
  observacao_queixa: 'Teste de observação',
  data_agendamento: '',
  guia_id: '10001125',
  hora: '11:15',
  especialidade: 'CLÍNICO GERAL',
  local_atendimento: 'CONJUNTO CEARA',
  atestado: 'Não',
  encaminhamento: 'Não',
  pedido_exames: 'Não',
  anamnese: '',
  data_assinatura: '16 de Novembro de 2020',
};

module.exports = data;
